language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: tSQU8RTNfoXsOGEZNrNFPp6g0fWJFsfvip7DEJ4QSw0kZ5t+8KvxI8re04QZyxMbtJEHWJ8RVzBthYWj1EvZd4ZgdXX13DOlvGtiHN7+QnurjBXF9mzJByzexzaNBrQUpSRt070pwcMsWeTFYh6eHPSiELkt2U++cQ5xK+5iqbhI/+bte7FNOksPaRL3i0eNaWCNTKE6w5sm/BcWVOvY8pIv1vHhByzqzD6snvoFhAIuMsI+mEjSd79Qo2kJjSFBbBPjlOTK70jkuL6P/ZLc5F6kp1pk6OuKnPd+W7BKNVCCiqOMjgt5Ov/2QPGxXWFTUB09GJuGTu7QWIcLnzA6CWgLsuSYdoFFTnx1IYvr3REyjJRRIllEoXJGhVILhBSC7Xy1L1wsEw4ESe/qbXVVrtYFhxaDLFyEDj9oY1ml2GTOttZpHoMjN2ANQ3B5FKu5TE63HhdJZbr80nukP07mSZBz9QDsMR3KqsEtn6NVpfuA9TLQF2Bheb6RbrGfAoAoQIccRoe6eevBohbDbxUAVdDt7GfoGTmaGy1cH+T/DfVJpItYdaIBMIEnJ4/28SHdoxXPh2Lg2jOC81ZC+x8mRaFUEcS4PGx5T+GSYWIzoZpPFUttnyDaDXt8Ew6apqQzUM0bPEuUiIzR+Hrx+jRUQruTyfItGtsy8Xz2Bgq6zw0=
  file:
    - 'remark-vdom.js'
    - 'remark-vdom.min.js'
  on:
    tags: true
